### ISSUE TITLE
please provide GRCh38 wget link

### ISSUE THREAD

**Issue by colindaven** [MCorentin/kilda#2]
Hi,

can you please provide the link to the exact human genome the software needs. I'm guessing the headers might be important.

Thanks.

**Comment by MCorentin** [comment]
Hi,

The software does not need any specific human genome.

A reference genome is needed for _kiv2_create_kmers_DB.nf_ but you can use the one of your choice (it just need to be coherent with the bed files you are using to delimitate the KIV-2 and normalisation regions).

For _kilda.nf_ a reference genome is only needed when you are giving BAM files as input (if so, then input the reference you used to produce the BAMs).

To produce the datasets in the _data/_ folder here, we used GRCh38, with renaming of the chromosomes as "chrX".

I hope this answers your question, I am closing the issue but feel free to reopen it if something is not clear.
